### ISSUE TITLE
During the development stage, there seems to be an issue with hot module replacement (HMR). 

### ISSUE THREAD

**Issue by WuChenDi** [Jonghakseo/chrome-extension-boilerplate-react-vite#108]
Hey guys, I have a question. 

During the local development phase, I noticed that after saving the changes, the browser displays an abnormal behavior and I have to refresh the browser to restore normalcy. 

How can I handle or avoid this situation? Is it a bug?

![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/31385662/d26eb7f2-df53-4694-94ea-a45f5e6763e7)
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/31385662/4a734ee1-6fa9-4c99-a070-041a13afe59d)

**Comment by WuChenDi** [comment]
This error occurs occasionally.

```bash
built in 545ms.

build started...
 Manifest file copy complete: C:\Users\dd\work\wudi\cdLab996\wallet-extension-vite\dist\manifest.json
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: EPERM: operation not permitted, stat 'C:\Users\dd\work\wudi\cdLab996\wallet-extension-vite\dist\src\pages\options\index.js'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\Users\dd\work\wudi\cdLab996\wallet-extension-vite\node_modules\.pnpm\chokidar@3.5.3\node_modules\chokidar\index.js:647:10)
    at NodeFsHandler._addToNodeFs (C:\Users\dd\work\wudi\cdLab996\wallet-extension-vite\node_modules\.pnpm\chokidar@3.5.3\node_modules\chokidar\lib\nodefs-handler.js:645:18) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\Users\\dd\\work\\wudi\\cdLab996\\wallet-extension-vite\\dist\\src\\pages\\options\\index.js'
}

Node.js v18.12.0
 ELIFECYCLE  Command failed with exit code 1.
✓ 75 modules transformed.
dist/assets/svg/imgLogo.chunk.svg                     2.62 KiB
dist/src/pages/devtools/index.html                    0.30 KiB
dist/src/pages/panel/index.html                       0.49 KiB
dist/src/pages/popup/index.html                       0.55 KiB
dist/src/pages/newtab/index.html                      0.55 KiB
dist/src/pages/options/index.html                     0.49 KiB
dist/src/pages/devtools/index.js                      0.18 KiB
dist/src/pages/panel/index.js                         0.67 KiB
dist/src/pages/content/index.js                       1.20 KiB
dist/src/pages/background/index.js                    1.56 KiB
dist/src/pages/popup/index.js                         1.23 KiB
dist/src/pages/newtab/index.js                        1.36 KiB
dist/src/pages/options/index.js                       0.63 KiB
dist/assets/js/modulepreload-polyfill.js              1.27 KiB
dist/assets/js/_virtual_reload-on-update-in-view.js   217.66 KiB
dist/assets/js/logo.js                                0.07 KiB
dist/assets/js/index.js                               0.54 KiB
dist/assets/css/panelIndex.chunk.css                  0.08 KiB
dist/assets/css/contentStyle16843791307.chunk.css     0.07 KiB
dist/assets/css/popupIndex.chunk.css                  1.13 KiB
dist/assets/css/newtabIndex.chunk.css                 1.00 KiB
dist/assets/css/optionsIndex.chunk.css                0.14 KiB
built in 519ms.
ERROR: "wss" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Jonghakseo** [comment]
I will check into this issue.

**Comment by Jonghakseo** [comment]
`Error: EPERM: operation not permitted.` This seems to be an error message in your vscode shell indicating a permission issue. Would you like to try again with administrator privileges?

**Comment by stone89son** [comment]
> `Error: EPERM: operation not permitted.` This seems to be an error message in your vscode shell indicating a permission issue. Would you like to try again with administrator privileges?

thank you. i run command by admin -> run prefect!

**Comment by stone89son** [comment]
> > `Error: EPERM: operation not permitted.` This seems to be an error message in your vscode shell indicating a permission issue. Would you like to try again with administrator privileges?
> 
> thank you. i run command by admin -> run prefect!

:( sorry, something happed to this error.

**Comment by Jonghakseo** [comment]
@stone89son 
Are you saying that the error persists after authorization?
