### ISSUE TITLE
EPERM Error: After making code changes like hardly 10 times it randomly crashes

### ISSUE THREAD

**Issue by twicer-is-coder** [Jonghakseo/chrome-extension-boilerplate-react-vite#132]
It automatically crashes. VS Code is ran as admin. This is actually making the boilerplate and reloading useless If I have to restart it almost after any change.

LOG:
build started...
 Manifest file copy complete: H:\User\Node.js\Test\dist\manifest.json
node:internal/process/promises:246
          ^

Error: EPERM: operation not permitted, stat 'H:\User\Node.js\Test\dist\assets\svg'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (H:\User\Node.js\Test\node_modules\chokidar\index.js:647:10)
    at NodeFsHandler._addToNodeFs (H:\User\Node.js\Test\node_modules\chokidar\lib\nodefs-handler.js:645:18) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'H:\\User\\Node.js\\Test\\dist\\assets\\svg'
}
ERROR: "wss" exited with 1.

**Comment by twicer-is-coder** [comment]
Workaround: Just wrapped the error emit handler of chokdar for EPERM in if to prevent it from throwing error.
