### ISSUE TITLE
Hot reload not working correctly

### ISSUE THREAD

**Issue by dasfullshitt** [Jonghakseo/chrome-extension-boilerplate-react-vite#142]
Hi!
I cloned your repository, installed dependencies and ran `yarn dev`, but when I try to make changes, an error crashes.
```powershell
yarn run v1.22.19
$ npm run build:hmr && (run-p wss build:watch)

> chrome-extension-boilerplate-react-vite@0.0.1 build:hmr
> rollup --config utils/reload/rollup.config.ts


utils/reload/initReloadServer.ts → utils/reload/initReloadServer.js...
created utils/reload/initReloadServer.js in 5.1s

utils/reload/injections/script.ts → utils/reload/injections/script.js...
created utils/reload/injections/script.js in 16ms

utils/reload/injections/view.ts → utils/reload/injections/view.js...
created utils/reload/injections/view.js in 20ms
$ node utils/reload/initReloadServer.js
$ cross-env __DEV__=true vite build --watch
[HRS] Server listening at ws://localhost:8081
vite v3.1.3 building for production...

watching for file changes...

build started...
 Manifest file copy complete: H:\Automatisation\chrome-extension-boilerplate-react-vite-0.0.8\dist\manifest.json
✓ 60 modules transformed.
dist/assets/svg/imgLogo.chunk.svg                     2.61 KiB
dist/src/pages/devtools/index.html                    0.29 KiB
dist/src/pages/panel/index.html                       0.48 KiB
dist/src/pages/popup/index.html                       0.54 KiB
dist/src/pages/newtab/index.html                      0.54 KiB
dist/src/pages/options/index.html                     0.48 KiB
dist/src/pages/devtools/index.js                      0.20 KiB
dist/src/pages/panel/index.js                         0.70 KiB
dist/src/pages/content/index.js                       1.20 KiB
dist/src/pages/background/index.js                    1.74 KiB
dist/src/pages/popup/index.js                         1.26 KiB
dist/src/pages/newtab/index.js                        1.51 KiB
dist/src/pages/options/index.js                       0.63 KiB
dist/assets/js/modulepreload-polyfill.js              1.27 KiB
dist/assets/js/_virtual_reload-on-update-in-view.js   217.84 KiB
dist/assets/js/logo.js                                0.07 KiB
dist/assets/js/index.js                               0.56 KiB
dist/assets/css/panelIndex.chunk.css                  10.02 KiB
dist/assets/css/contentStyle16879417681.chunk.css     10.03 KiB
dist/assets/css/popupIndex.chunk.css                  11.02 KiB
dist/assets/css/newtabIndex.chunk.css                 10.90 KiB
dist/assets/css/optionsIndex.chunk.css                10.08 KiB
built in 13480ms.

build started...
node:fs:1226
  return handleErrorFromBinding(ctx);
         ^

Error: ENOTEMPTY: directory not empty, rmdir '\\?\H:\Automatisation\chrome-extension-boilerplate-react-vite-0.0.8\dist\assets'
    at Object.rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:260:21)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmSync (node:fs:1275:10)
    at emptyDir (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/dist/node/chunks/dep-557f29e6.js:12007:14)
    at prepareOutDir (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/dist/node/chunks/dep-557f29e6.js:45839:13)
    at WatchEmitter.<anonymous> (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/dist/node/chunks/dep-557f29e6.js:45791:25)
    at WatchEmitter.emit (node:events:513:28)
    at Task.run (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/node_modules/rollup/dist/es/shared/watch.js:4932:30)
    at Watcher.run (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/node_modules/rollup/dist/es/shared/watch.js:4871:24)
    at Timeout._onTimeout (file:///H:/Automatisation/chrome-extension-boilerplate-react-vite-0.0.8/node_modules/vite/node_modules/rollup/dist/es/shared/watch.js:4850:22) {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '\\\\?\\H:\\Automatisation\\chrome-extension-boilerplate-react-vite-0.0.8\\dist\\assets'
}
```

What am I doing wrong? I also tried running `yarn dev` with administrator rights, but it didn't help.

**Comment by Jonghakseo** [comment]
Thanks for the report. Is it possible to get information about the node version?

**Comment by Jonghakseo** [comment]
Close it for issue management. Anyone can reopen it for similar or identical issue raising.

**Comment by dasfullshitt** [comment]
Sorry for the long reaction.
```powershell
node -v
v18.17.0
```
