### ISSUE TITLE
Right after checkout, project won't build

### ISSUE THREAD

**Issue by hakunin** [Jonghakseo/chrome-extension-boilerplate-react-vite#29]
Hi, any idea what this is complaining about?

```
> yarn dev
yarn run v1.22.15
$ yarn build:hmr && (yarn wss & nodemon)
$ rollup --config utils/reload/rollup.config.ts

utils/reload/initReloadServer.ts → utils/reload/initReloadServer.js...
created utils/reload/initReloadServer.js in 2.4s

lib/reload/initReloadClient.ts → lib/reload/initReloadClient.js...
[!] Error: Could not resolve entry module (lib/reload/initReloadClient.ts).
Error: Could not resolve entry module (lib/reload/initReloadClient.ts).
    at error (/home/michal/dev/quantloupe-vite/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/home/michal/dev/quantloupe-vite/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hakunin** [comment]
Going into the file and removing this part:
```
  {
    plugins,
    input: "lib/reload/initReloadClient.ts",
    output: {
      file: "lib/reload/initReloadClient.js",
    },
  },
```
Makes it go through and build.

**Comment by Jonghakseo** [comment]
I'm sorry.

Late recognition of the inclusion of unnecessary lines in the process of merging PR. I solved the problem through the commit below, so I think we can solve the problem through pull.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/commit/815b8959fde8f954336ceb3701c740d37a459b05

**Comment by hakunin** [comment]
Cool, thanks!

**Comment by Jonghakseo** [comment]
@all-contributors please add @hakunin for bug
