### ISSUE TITLE
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL 

### ISSUE THREAD

**Issue by androozhang** [Jonghakseo/chrome-extension-boilerplate-react-vite#536]
**Describe the bug**
> @chrome-extension-boilerplate/hmr@0.0.1 dev /Users/droo/Desktop/github/curate-extension/packages/hmr
> node dist/lib/initReloadServer.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at new WebSocketServer (/Users/droo/Desktop/github/curate-extension/node_modules/.pnpm/ws@8.17.1/node_modules/ws/lib/websocket-server.js:102:20)
    at initReloadServer (/Users/droo/Desktop/github/curate-extension/packages/hmr/dist/lib/initReloadServer.js:13:21)
    at Object.<anonymous> (/Users/droo/Desktop/github/curate-extension/packages/hmr/dist/lib/initReloadServer.js:36:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:514:28)
    at emitErrorNT (node:net:1899:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8081
}

**To Reproduce**

  1. git clone
  2. pnpm i
  3. pnpm run dev

**Expected behavior**
pnpm dev works correctly 

**Screenshots**
<img width="1168" alt="Screenshot 2024-06-29 at 1 11 34 AM" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/82245268/f3a73bac-2e63-4566-a982-b10651770928">

**Desktop (please complete the following information):**
 - OS: [Mac M2]
 - Browser [chrome]
 - Node Version [v20.10.0]

**Additional context**
none

**Comment by Jonghakseo** [comment]
```bash
Error: listen EADDRINUSE: address already in use :::8081
```
It looks like already used that port. 

If you want to exit all process with port 8081, run this command into your shell. :)

```bash
$ lsof -ti tcp:8081 | xargs kill -9
```

**Comment by androozhang** [comment]
<img width="1060" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/82245268/5cccb090-d9e7-4555-aec8-ee78aa3e43f7">
Im getting this error where pnpm dev doesn't finish. I'm new to browser extension, but is this how it's suppose to be?

**Comment by Jonghakseo** [comment]
@androozhang In the dev mode, it is normal for changes in files to be detected and rebuilt using persistence, so everything is working as intended.
